name: Java CI Workflow

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #step 1: Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      #step 2: Set up Java jdk 22
      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven

      #step 3: build the project with maven
      - name: Build with Maven
        run: mvn clean compile

      # Step 4: Run tests with detailed logging
      - name: Run tests
        run: mvn test -e -X

      # Step 5: Upload Surefire reports for debugging failed tests
      - name: Upload Surefire Reports
        if: failure() # Only upload if a step fails
        uses: actions/upload-artifact@v3
        with:
          name: surefire-reports
          path: target/surefire-reports

      # Step 6: Package the application
      - name: Package Application
        run: mvn package -DskipTests


